### ISSUE TITLE
feat : update Ditto doc/Readme 📖

### ISSUE THREAD

**Issue by Tbelleng** [KasarLabs/ditto#23]
**# Issue: Update Ditto doc/Readme**

**# Description:**
Ditto is a crucial resource for testing Deoxys, however, it has come that some parts of the documentation or README may not be fully up-to-date with the latest developments and features of Ditto.

In order to provide clear and current guidance, it would be beneficial to perform a comprehensive review and update of the documentation. This update should aim to ensure that all instructions, examples, and references accurately reflect the current state of the Ditto project.

**# Comments:**
Please comment below for coordination.

**Comment by antiyro** [comment]
can we close this with #25? @Tbelleng
