### ISSUE TITLE
bump starknet.rs version to maintain compatibility with Deoxys

### ISSUE THREAD

**Issue by antiyro** [KasarLabs/ditto#30]
Please bump ditto to https://github.com/xJonathanLEI/starknet-rs/commit/96c6803118773d9fd1d74fcf1465763f11a080a1

**Comment by Tbelleng** [comment]
**Issue :**

Its seems that this commit #https://github.com/xJonathanLEI/starknet-rs/commit/4107312482257921d52a1fc86797c71f81703527 changed the error management for starknet-rs (by deleting the "MaybeUnknownErrorCode" part). We have to switch from "MaybeUnknownErrorCode" to "StarknetError" to restore full compatibility.

Im gonna take this one

**Comment by antiyro** [comment]
solved by #29
