### ISSUE TITLE
feat(rpc): Bump testing to v0.6 ⬆️

### ISSUE THREAD

**Issue by Tbelleng** [KasarLabs/ditto#51]
# Bump Ditto to v0.6 RPC format

- v3 Transactions testing
- manage stricter restrictions on v3 Fields
- manage FRI (Stark gas unit) in fee and message fee testing

**Comment by mubarak23** [comment]
@Tbelleng Please i will like to work on this issue

**Comment by Tbelleng** [comment]
Hi sir @mubarak23 !
Thanks you for your proposition.
This issue will be available when v0.6 RPC call will be live on Deoxys ! 👽

**Comment by mubarak23** [comment]
@Tbelleng  Alright, i will wait until then in the main time, i will look out for other issues i can work on.
